<?php

namespace Cachet\Database\Seeders;

use Cachet\Enums\IncidentTemplateEngineEnum;
use Cachet\Models\IncidentTemplate;
use Illuminate\Database\Seeder;

/**
 * Seeder for Uptime Kuma incident templates.
 * 
 * These templates are used for automatic incident creation and resolution
 * when services go down or recover.
 */
class UptimeKumaTemplatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Service Outage Template
        IncidentTemplate::updateOrCreate(
            ['slug' => 'service-outage'],
            [
                'name' => 'Service Outage (Automated)',
                'engine' => IncidentTemplateEngineEnum::twig,
                'template' => $this->getOutageTemplate(),
            ]
        );

        // Service Recovery Template
        IncidentTemplate::updateOrCreate(
            ['slug' => 'service-recovery'],
            [
                'name' => 'Service Recovery (Automated)',
                'engine' => IncidentTemplateEngineEnum::twig,
                'template' => $this->getRecoveryTemplate(),
            ]
        );

        // Manual Maintenance Template
        IncidentTemplate::updateOrCreate(
            ['slug' => 'scheduled-maintenance'],
            [
                'name' => 'Scheduled Maintenance',
                'engine' => IncidentTemplateEngineEnum::twig,
                'template' => $this->getMaintenanceTemplate(),
            ]
        );

        // Manual Investigation Template
        IncidentTemplate::updateOrCreate(
            ['slug' => 'investigating-issue'],
            [
                'name' => 'Investigating Issue',
                'engine' => IncidentTemplateEngineEnum::twig,
                'template' => $this->getInvestigatingTemplate(),
            ]
        );
    }

    /**
     * Get the outage template content.
     */
    protected function getOutageTemplate(): string
    {
        return <<<'TEMPLATE'
## Service Disruption Detected

**Affected Service:** {{ component_name }}

**Status:** Investigating

**Detected:** {{ occurred_at }}

---

### Details

Our monitoring systems have detected an issue with **{{ service_name }}**.

{% if url %}
- **Endpoint:** `{{ url }}`
{% endif %}
- **Error:** {{ error_message }}
{% if ping %}
- **Last Response Time:** {{ ping }}ms
{% endif %}

---

### What's Next?

Our team has been alerted and is actively investigating the issue. We will provide updates as more information becomes available.

_This incident was automatically detected by our monitoring system._
TEMPLATE;
    }

    /**
     * Get the recovery template content.
     */
    protected function getRecoveryTemplate(): string
    {
        return <<<'TEMPLATE'
## Service Restored

**Status:** Resolved

**Resolved:** {{ resolved_at }}

**Total Downtime:** {{ duration }}

---

The service has been restored and is now operating normally. We apologize for any inconvenience this may have caused.

If you continue to experience issues, please contact our support team.

_This update was automatically generated by our monitoring system._
TEMPLATE;
    }

    /**
     * Get the scheduled maintenance template content.
     */
    protected function getMaintenanceTemplate(): string
    {
        return <<<'TEMPLATE'
## Scheduled Maintenance

**Service:** {{ service_name | default('Multiple Services') }}

**Scheduled Time:** {{ start_time | default('TBD') }} - {{ end_time | default('TBD') }}

---

### What to Expect

We will be performing scheduled maintenance on our systems. During this time, you may experience:

- Brief interruptions in service
- Slower response times
- Temporary unavailability of certain features

---

### Impact

{{ impact_description | default('Minimal impact expected. Most services will remain available.') }}

---

We appreciate your patience as we work to improve our services.

_This is a planned maintenance window._
TEMPLATE;
    }

    /**
     * Get the investigating template content.
     */
    protected function getInvestigatingTemplate(): string
    {
        return <<<'TEMPLATE'
## Investigating Issue

**Service:** {{ service_name | default('Unknown Service') }}

**Status:** Investigating

**Reported:** {{ reported_at | default('Just now') }}

---

### Summary

We are currently investigating reports of {{ issue_type | default('service degradation') }}.

### Current Status

{{ status_description | default('Our team is actively looking into this issue.') }}

---

### What We Know So Far

{{ details | default('Investigation is underway. More details will be provided as they become available.') }}

---

We will update this incident as more information becomes available.
TEMPLATE;
    }
}
