<?php

declare(strict_types=1);

namespace Cachet\Http\Resources;

use Illuminate\Http\Request;
use TiMacDonald\JsonApi\JsonApiResource;

class Tag extends JsonApiResource
{
    public function toAttributes(Request $request): array
    {
        return parent::toAttributes($request); // TODO: Change the autogenerated stub
    }
}
