<?php

namespace Cachet\Data\Incident;

use Cachet\Data\BaseData;
use Cachet\Enums\IncidentStatusEnum;
use Spatie\LaravelData\Attributes\Validation\Enum;
use Spatie\LaravelData\Attributes\Validation\Max;
use Spatie\LaravelData\Attributes\Validation\Sometimes;
use Spatie\LaravelData\Attributes\Validation\StringType;
use Spatie\LaravelData\Optional;

final class UpdateIncidentData extends BaseData
{
    public function __construct(
        #[Max(255), StringType, Sometimes]
        public readonly Optional|string $name,
        #[StringType, Sometimes]
        public readonly ?string $message = null,
        #[Enum(IncidentStatusEnum::class)]
        public readonly ?IncidentStatusEnum $status = null,
        public readonly ?bool $visible = null,
        public readonly ?bool $stickied = null,
        public readonly ?bool $notifications = null,
        public readonly ?string $occurredAt = null,
    ) {}

    public function toArray(): array
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}
